export const CHANGE_CITY = "CHANGE_CITY";
export const CHANGE_THEME = "CHANGE_THEME";
export const LOAD_CITIES = "LOAD_CITIES";
export const LOAD_PRAYERS = "LOAD_PRAYERS";
export const CHANGE_PERIOD = "CHANGE_PERIOD";
export const REFRESH_TIME = "REFRESH_TIME";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const INITIAL_INIT = "INITIAL_INIT";
